In [1]:
import numpy as np

In [4]:
NumP_Array = np.array([[1,2,3], [4,5,6]])
NumP_Array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
NP1 = np.array([[1,3],[4,5]])
NP1

array([[1, 3],
       [4, 5]])

In [8]:
NP2 = np.array([[3,4],[5,6]])
NP2

array([[3, 4],
       [5, 6]])

In [12]:
# Multiplication of 2 matrices - This is the dot product
MNP = NP1@NP2
MNP

array([[18, 22],
       [37, 46]])

In [16]:
# Dot product that is the normal algebra multiplication of 2 matrices
MNP3 = np.dot(NP1, NP2)
MNP3

array([[18, 22],
       [37, 46]])

In [14]:
# Element by element multiplication
MNP2 = NP1*NP2
MNP2

array([[ 3, 12],
       [20, 30]])

In [18]:
# This is the element by element multiplication
MNP4 = np.multiply(NP1, NP2)
MNP4

array([[ 3, 12],
       [20, 30]])

In [20]:
# Summation of matrices
Sum1 = NP1 + NP2
Sum1

array([[ 4,  7],
       [ 9, 11]])

In [22]:
# Substracting of matrices
Sub1 = NP1 - NP2
Sub1

array([[-2, -1],
       [-1, -1]])

In [25]:
# Substracting using numpy lib
Sub2 = np.subtract(NP1, NP2)
Sub2

array([[-2, -1],
       [-1, -1]])

In [30]:
# Sum all elements of a matrix
El_Sum = np.sum(NP1)
El_Sum

13

In [32]:
# Broadcasting: change a # into an array that fits the first array to operate with
Broad_Nump = NP1+3
Broad_Nump

array([[4, 6],
       [7, 8]])

In [33]:
NP3 = np.array([[3,4]])

In [36]:
# Broadcasting with more rows
Broad_Nump2 = NP1+NP3
Broad_Nump2

array([[4, 7],
       [7, 9]])

In [38]:
# Division of 2 matrices
D = np.divide(NP1,NP2)
D

array([[0.33333333, 0.75      ],
       [0.8       , 0.83333333]])

In [40]:
D2 = np.divide([12,14,16], 5)
D2

array([2.4, 2.8, 3.2])

In [43]:
# Having integer only
D3 = np.floor_divide([12,14,16], 5)
D3

array([2, 2, 3])

In [47]:
# Square operation
Sq = np.math.sqrt(10)
Sq

3.1622776601683795

In [48]:
# Generating different distributions

In [52]:
# These are no random #s, they are from a distribution
Norm_Dist = np.random.standard_normal((3,4))
Norm_Dist

array([[-1.81958531, -0.86624292,  1.37802863, -0.75644291],
       [-0.88267412,  0.04800965, -0.15207279, -0.94367826],
       [ 0.36387751,  0.34237125, -0.84460956, -0.92088069]])

In [51]:
Unif_Dist = np.random.uniform(1,12,(3,4))
Unif_Dist

array([[ 2.47091454,  7.4394215 ,  2.82585805,  5.66970929],
       [ 1.1902979 ,  1.87520303,  4.07026975,  5.70768915],
       [11.18843488,  6.99957892, 10.91060169,  6.301363  ]])

In [61]:
# Random float number between 0, 1
# I want random #s
Random_Float_Ar = np.random.rand(2,5) #.rand() -> gives float #s
Random_Ar = np.random.randint(1,50,(2,5))  #.randint() -> gives int #s

In [62]:
Random_Ar

array([[11,  6, 47, 21,  6],
       [36, 42, 30, 44, 41]])

In [63]:
Random_Float_Ar

array([[0.10761947, 0.43697869, 0.08042964, 0.41577021, 0.04486043],
       [0.15479635, 0.90746241, 0.64275399, 0.78602628, 0.97051381]])

In [65]:
# Zero matrix
Ze = np.zeros((3,4))
Ze

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
# Ones matrix
Ones = np.ones((3,4))
Ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
# Filters
Filter_Ar = np.logical_and(Random_Ar>30, Random_Ar<50)
Filter_Ar

array([[False, False,  True, False, False],
       [ True,  True, False,  True,  True]])

In [73]:
# For having the #s I filtered out
F_Random_Ar = Random_Ar[Filter_Ar]
F_Random_Ar

array([47, 36, 42, 44, 41])

### Statistics